steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "$BRANCH_NAME"
- id: 'install checkov'
  name: 'python:3.9'
  entrypoint: 'bash'
  args:
      - '-c'
      - |
       
        pip install --upgrade pip
        pip install checkov
        checkov --version
        cd terraform_infra/
        checkov -d . --skip-check CKV_GCP_113,CKV_GCP_60,CKV_GCP_14,CKV2_GCP_20,CKV_GCP_6,CKV_GCP_79 --output json --output-file checkov_report.json --quiet || (echo "Checkov scan failed!" && exit 1) 

- id: 'tf init'
  name: "hashicorp/terraform:1.3.0"
  entrypoint: 'sh'
  args:
  - '-c'
  - |
        if [ -d "$_PATH_TF"]; then
          echo "run init"
          cd terraform_infra/
          terraform init -reconfigure
        else
          for dir in $_PATH_TF
          do
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo "${env}"
          terraform init -reconfigure|| exit 1
        done
        fi
- id: 'tf plan'
  name: "hashicorp/terraform:1.3.0"
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ -d "$_PATH_TF"]; then
        cd terraform_infra/       
        echo "run plan"
        terraform refresh
        terraform plan
      else
        for dir in $_PATH_TF
        do
          cd ${dir}
          env=${dir%*/}
          env=${env#*/}
          echo "${env}"
          terraform plan || exit 1
        done
      fi

- id: 'tf apply or destroy'
  name: "hashicorp/terraform:1.3.0"
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ -d "$_PATH_TF" ]; then
         cd terraform_infra/
         terraform $_TFACTION -auto-approve
      else
         echo "$BRANCH_NAME"
      fi
    
#timeout = 6100s
logsBucket: 'terraformbackendmysqlapplication'
options:
  logging: GCS_ONLY